### PR TITLE
pypi: add release setup

### PR DESCRIPTION
**Pull request by mougams**

### CODE REVIEW

**Comment by wdauchy** [comment]
is it tested, at least on a branch?

**Comment by mougams** [comment]
> is it tested, at least on a branch?

Nope - and will do

**Comment by wdauchy** [comment]
> > is it tested, at least on a branch?
> 
> Nope - and will do

any news about it?

**Comment by mougams** [comment]
> > > is it tested, at least on a branch?
> > 
> > 
> > Nope - and will do
> 
> any news about it?

I'm not sure how to publish in public repo without interfering the version.
I followed the doc/some examples for this - can we instead merge and iterate if that fails?

**Review by wdauchy — APPROVED** [review]
I was thinking about publish/delete but fair enough if too complicated or not possible

**Pull request merged**
